import {
  center,
  colorways,
  exposedFaces,
  FACE_LABEL,
  FACE_NORMALS,
  FaceColors,
  faceCorners,
  FaceId,
  isVisibleFace,
  Vec3,
  VoxelModel,
} from '@constructive-io/brand-geometry';

/** Material slot per face orientation. Hidden faces (-x,-y,-z) reuse the opposite visible slot. */
export type MaterialName = 'top' | 'left' | 'right';

export interface MeshFace {
  /** Indices into `vertices` (0-based), counter-clockwise from outside. */
  indices: [number, number, number, number];
  normal: Vec3;
  material: MaterialName;
  face: FaceId;
  /** Index of the source voxel; set when `topology: 'cubes'`. */
  group?: number;
}

export interface Mesh {
  vertices: Vec3[];
  faces: MeshFace[];
  materials: Record<MaterialName, string>;
}

/**
 * `shell`: one watertight surface, faces between touching cubes culled, vertices shared.
 * `cubes`: every voxel is a complete closed cube with its own vertices, grouped per cube.
 */
export type MeshTopology = 'shell' | 'cubes';

export interface MeshOptions {
  /** Edge length in world units. */
  size?: number;
  topology?: MeshTopology;
  /** Translate so the bounding box is centred on the origin. */
  center?: boolean;
  colors?: Partial<FaceColors>;
}

const OPPOSITE: Record<FaceId, MaterialName> = {
  '+z': 'top',
  '-z': 'top',
  '+y': 'left',
  '-y': 'left',
  '+x': 'right',
  '-x': 'right',
};

/**
 * Build a quad mesh from a voxel model. Default `shell` topology emits only faces
 * touching air and deduplicates shared vertices; `cubes` keeps every cube whole.
 */
export function buildMesh(model: VoxelModel, opts: MeshOptions = {}): Mesh {
  const size = opts.size ?? 1;
  const topology = opts.topology ?? 'shell';
  const c = opts.center ? center(model) : { x: 0, y: 0, z: 0 };
  const colors: FaceColors = { ...colorways.solid, ...opts.colors };

  const vertices: Vec3[] = [];
  const index = new Map<string, number>();
  const vertex = (p: Vec3, group: number): number => {
    const key = `${topology === 'cubes' ? `${group}:` : ''}${p.x},${p.y},${p.z}`;
    let i = index.get(key);
    if (i === undefined) {
      i = vertices.length;
      index.set(key, i);
      vertices.push({ x: (p.x - c.x) * size, y: (p.y - c.y) * size, z: (p.z - c.z) * size });
    }
    return i;
  };

  const groupOf = new Map<Vec3, number>(model.voxels.map((v, i) => [v, i]));
  const source =
    topology === 'cubes'
      ? model.voxels.flatMap((voxel) => (Object.keys(FACE_NORMALS) as FaceId[]).map((face) => ({ voxel, face })))
      : exposedFaces(model);

  const faces: MeshFace[] = source.map(({ voxel, face }) => {
    const group = groupOf.get(voxel) ?? 0;
    const [a, b, cc, d] = faceCorners(voxel, face);
    return {
      indices: [vertex(a, group), vertex(b, group), vertex(cc, group), vertex(d, group)],
      normal: FACE_NORMALS[face],
      material: isVisibleFace(face) ? FACE_LABEL[face] : OPPOSITE[face],
      face,
      ...(topology === 'cubes' ? { group } : {}),
    };
  });

  return { vertices, faces, materials: { top: colors.top, left: colors.left, right: colors.right } };
}

/** Triangle index list (two per quad) for GPU buffers. */
export function triangulate(mesh: Mesh): number[] {
  const out: number[] = [];
  for (const { indices: [a, b, c, d] } of mesh.faces) out.push(a, b, c, a, c, d);
  return out;
}

/** Flat position array (xyz per vertex). */
export function positions(mesh: Mesh): number[] {
  const out: number[] = [];
  for (const v of mesh.vertices) out.push(v.x, v.y, v.z);
  return out;
}

export interface ObjOptions {
  /** Object name written as `o <name>`. */
  name?: string;
  /** File referenced by `mtllib`; omit to skip materials. */
  mtllib?: string;
  /** Swap Y and Z so +Y is up (three.js / Blender default). */
  yUp?: boolean;
  precision?: number;
}

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.replace('#', ''), 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
}

const f = (n: number, p: number): string => {
  const s = n.toFixed(p);
  return s === `-${(0).toFixed(p)}` ? (0).toFixed(p) : s;
};

/**
 * Wavefront OBJ. Vertices are 1-based; each quad is one `f` line; `cubes` meshes get one `g` per cube.
 *
 * Brand space is left-handed as seen from the isometric camera (+x screen-right, +y screen-left), so
 * x and y are swapped on the way out — the same mapping the WebGL renderer uses — and quads are
 * re-wound so they stay counter-clockwise from outside. Viewed from the (1,1,1) diagonal in any
 * right-handed tool the mesh then matches the SVG exactly.
 */
export function toObj(mesh: Mesh, opts: ObjOptions = {}): string {
  const { name = 'constructive', mtllib, yUp = true, precision = 4 } = opts;
  const swap = (v: Vec3): Vec3 => {
    const r = { x: v.y, y: v.x, z: v.z };
    return yUp ? { x: r.x, y: r.z, z: -r.y } : r;
  };
  const lines: string[] = ['# Constructive brand kit — generated by @constructive-io/brand-3d'];
  if (mtllib) lines.push(`mtllib ${mtllib}`);
  lines.push(`o ${name}`);

  for (const v of mesh.vertices) {
    const s = swap(v);
    lines.push(`v ${f(s.x, precision)} ${f(s.y, precision)} ${f(s.z, precision)}`);
  }

  const normals: Vec3[] = [];
  const normalIndex = new Map<string, number>();
  const normalOf = (n: Vec3): number => {
    const s = swap(n);
    const key = `${s.x},${s.y},${s.z}`;
    let i = normalIndex.get(key);
    if (i === undefined) {
      i = normals.length + 1;
      normalIndex.set(key, i);
      normals.push(s);
    }
    return i;
  };
  const faceNormals = mesh.faces.map((face) => normalOf(face.normal));
  for (const n of normals) lines.push(`vn ${f(n.x, 0)} ${f(n.y, 0)} ${f(n.z, 0)}`);

  let current: MaterialName | undefined;
  let group: number | undefined;
  mesh.faces.forEach((face, i) => {
    if (face.group !== undefined && face.group !== group) {
      group = face.group;
      lines.push(`g cube_${group}`);
      current = undefined;
    }
    if (mtllib && face.material !== current) {
      current = face.material;
      lines.push(`usemtl ${current}`);
    }
    const vn = faceNormals[i];
    lines.push('f ' + [...face.indices].reverse().map((idx) => `${idx + 1}//${vn}`).join(' '));
  });

  return lines.join('\n') + '\n';
}

/** Wavefront MTL with one diffuse material per face slot. */
export function toMtl(mesh: Mesh): string {
  const lines: string[] = ['# Constructive brand kit — generated by @constructive-io/brand-3d'];
  for (const [name, hex] of Object.entries(mesh.materials) as [MaterialName, string][]) {
    const [r, g, b] = hexToRgb(hex);
    lines.push('', `newmtl ${name}`, `Kd ${f(r, 4)} ${f(g, 4)} ${f(b, 4)}`, 'Ka 0.0000 0.0000 0.0000', 'Ks 0.0500 0.0500 0.0500', 'Ns 10', 'd 1.0', 'illum 2');
  }
  return lines.join('\n') + '\n';
}

export interface ExportResult {
  obj: string;
  mtl: string;
  mesh: Mesh;
}

/** OBJ + MTL pair for any voxel model. */
export function exportObj(model: VoxelModel, name: string, opts: MeshOptions & Omit<ObjOptions, 'name' | 'mtllib'> = {}): ExportResult {
  const { yUp, precision, ...meshOpts } = opts;
  const mesh = buildMesh(model, { center: true, ...meshOpts });
  return { mesh, obj: toObj(mesh, { name, mtllib: `${name}.mtl`, yUp, precision }), mtl: toMtl(mesh) };
}

